package main

import (
	"github.com/spf13/cobra"
	"github.com/theoparis/tav/internal/tav"
)

func newPushCmd() *cobra.Command {
	opts := tav.PushOptions{Remote: "origin"}
	c := &cobra.Command{
		Use:   "push",
		Short: "Push selected revisions",
		RunE: func(cmd *cobra.Command, args []string) error {
			return tav.Push(".", opts)
		},
	}
	c.Flags().StringVar(&opts.Remote, "remote", "origin", "remote name")
	c.Flags().StringSliceVarP(&opts.Revisions, "revisions", "r", nil, "push selected revisions via existing branches")
	c.Flags().StringSliceVarP(&opts.Create, "create", "c", nil, "push selected revisions to autogenerated branches")
	return c
}

func newAdvanceCmd() *cobra.Command {
	opts := tav.AdvanceOptions{Remote: "origin", Revset: "@-"}
	c := &cobra.Command{
		Use:   "advance",
		Short: "Advance a remote bookmark/branch to a revision",
		RunE: func(cmd *cobra.Command, args []string) error {
			return tav.Advance(".", opts)
		},
	}
	c.Flags().StringVar(&opts.Remote, "remote", "origin", "remote name")
	c.Flags().StringVarP(&opts.Bookmark, "bookmark", "b", "", "bookmark/branch name")
	c.Flags().StringVar(&opts.Bookmark, "branch", "", "bookmark/branch name")
	c.Flags().StringVarP(&opts.Revset, "revision", "r", "@-", "revision to advance to")
	c.Flags().BoolVar(&opts.Force, "force", false, "force push non-fast-forward updates")
	return c
}
